#!/usr/bin/env bash
# Script which will display info of the subdomain

query_dns() {
    dig "$1"."$2" | awk '/ANSWER SECTION/ {getline; print $4}'
}

display_info() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(query_dns "$sub" "$domain")
        echo "The subdomain $sub is a $record_type record and points to $(query_dns "$sub" "$domain")"
    done
}


if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

display_info "$1" "$2"
