#!/usr/bin/env bash
# Configs nginx web server for custom 404

apt-get update
apt-get install -y nginx
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;;
    index  index.html;
    location /redirect_me {
        return 301 https://youtube.com/syandam;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
