#!/usr/bin/env bash
# THIS SCRIPT:
# CREATES THE FILE /VAR/RUN/MYSCRIPT.PID CONTAINING ITS PID

# DISPLAYS TO INFINITY AND BEYOND INDEFINITELY

# DISPLAYS I HATE THE KILL COMMAND WHEN RECEIVING A SIGTERM SIGNAL

# DISPLAYS Y U NO LOVE ME?! WHEN RECEIVING A SIGINT SIGNAL

# DELETES THE FILE /VAR/RUN/MYSCRIPT.PID AND TERMINATES ITSELF WHEN

# RECEIVING A SIGQUIT OR SIGTERM SIGNAL

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

while true
do 
    echo 'To infinity and beyond' 
    sleep 2
done