#!/usr/bin/env bash
# THIS SCRIPT DISPLAYS NUMBERS FROM 1 TO 100 IN LIST FORMAT
#   DISPLAYS "FIZZBUZZ" WHEN THE NUMBER IS A MULTIPLE OF 3 AND 5
#   DISPLAYS "FIZZ" WHEN THE NUMBER IS A MULTIPLE OF 3
#   DISPLAYS "BUZZ" WHEN THE NUMBER IS A MULTIPLE OF 5
#   OTHERWISE, DISPLAYS THE NUMBER


COUNTER=1
while [ $COUNTER -lt 101 ]
do
    if [ $((COUNTER%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((COUNTER%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((COUNTER%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$COUNTER"
    fi
    let COUNTER+=1
done
