#!/usr/bin/env bash
# A SCRIPT THAT DISPLAYS BEST SCHOOL 10 TIMES AND HI AFTER THE 9TH USING WHILE AND IF

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done