#!/usr/bin/env bash
# This script sets up an Ubuntu server with the following configurations:
# - localhost is configured to resolve to 127.0.0.2
# - facebook.com is configured to resolve to 8.8.8.8

sudo echo "127.0.0.2 localhost" >> /etc/hosts
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts