#!/usr/bin/env bash
# This script sets up an Ubuntu server with the following configurations:
# - localhost is configured to resolve to 127.0.0.2
# - facebook.com is configured to resolve to 8.8.8.8


cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts