#!/usr/bin/env bash
# Configures Nginx to run as the nginx user and listen on port 8080

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill the process if it is running
pkill apache2
# Restart Nginx to apply the changes
sudo -u nginx service nginx start
